/*
 * Inhalte der Bibliothek.
 * Allgemeine Informationen, zusammengestellt nach öffentlich zugänglichen,
 * seriösen Quellen (IQWiG / gesundheitsinformation.de, BZgA / kindergesundheit-info.de,
 * infektionsschutz.de, NHS). Kein Ersatz für ärztlichen Rat.
 */

const SYMPTOMS = [
  { id: 'fieber', label: 'Fieber', group: 'Allgemein' },
  { id: 'muedigkeit', label: 'Müdigkeit / schlapp', group: 'Allgemein' },
  { id: 'appetitlosigkeit', label: 'Appetitlosigkeit', group: 'Allgemein' },
  { id: 'trinkschwaeche', label: 'Trinkt wenig', group: 'Allgemein' },
  { id: 'unruhe', label: 'Unruhe / viel Weinen', group: 'Allgemein' },
  { id: 'lymphknoten', label: 'Geschwollene Lymphknoten', group: 'Allgemein' },
  { id: 'kopfschmerzen', label: 'Kopfschmerzen', group: 'Allgemein' },
  { id: 'krampf', label: 'Krampfanfall', group: 'Allgemein' },

  { id: 'schnupfen', label: 'Schnupfen', group: 'Atemwege & HNO' },
  { id: 'husten', label: 'Husten', group: 'Atemwege & HNO' },
  { id: 'bellender-husten', label: 'Bellender Husten', group: 'Atemwege & HNO' },
  { id: 'hustenanfaelle', label: 'Hustenanfälle', group: 'Atemwege & HNO' },
  { id: 'atemnot', label: 'Schnelle / schwere Atmung', group: 'Atemwege & HNO' },
  { id: 'halsschmerzen', label: 'Halsschmerzen', group: 'Atemwege & HNO' },
  { id: 'ohrenschmerzen', label: 'Ohrenschmerzen', group: 'Atemwege & HNO' },
  { id: 'heiserkeit', label: 'Heiserkeit', group: 'Atemwege & HNO' },

  { id: 'erbrechen', label: 'Erbrechen', group: 'Bauch' },
  { id: 'durchfall', label: 'Durchfall', group: 'Bauch' },
  { id: 'bauchschmerzen', label: 'Bauchschmerzen', group: 'Bauch' },
  { id: 'brennen-wasserlassen', label: 'Brennen beim Wasserlassen', group: 'Bauch' },

  { id: 'ausschlag', label: 'Hautausschlag', group: 'Haut, Mund & Augen' },
  { id: 'blaeschen', label: 'Bläschen auf der Haut', group: 'Haut, Mund & Augen' },
  { id: 'juckreiz', label: 'Juckreiz', group: 'Haut, Mund & Augen' },
  { id: 'trockene-haut', label: 'Trockene Haut', group: 'Haut, Mund & Augen' },
  { id: 'rote-wangen', label: 'Rote Wangen', group: 'Haut, Mund & Augen' },
  { id: 'mund-blaeschen', label: 'Bläschen / Wunden im Mund', group: 'Haut, Mund & Augen' },
  { id: 'himbeerzunge', label: 'Himbeerzunge', group: 'Haut, Mund & Augen' },
  { id: 'sabbern', label: 'Vermehrtes Sabbern', group: 'Haut, Mund & Augen' },
  { id: 'schwellung-wange', label: 'Schwellung vor dem Ohr', group: 'Haut, Mund & Augen' },
  { id: 'rote-augen', label: 'Rote Augen', group: 'Haut, Mund & Augen' },
  { id: 'augen-verklebt', label: 'Verklebte Augen / Ausfluss', group: 'Haut, Mund & Augen' },
  { id: 'kopfjucken', label: 'Juckende Kopfhaut', group: 'Haut, Mund & Augen' },
  { id: 'windelbereich', label: 'Rötung im Windelbereich', group: 'Haut, Mund & Augen' }
];

const CATEGORIES = {
  atemwege: { label: 'Atemwege & HNO', color: 'sky' },
  bauch: { label: 'Magen & Darm', color: 'sage' },
  haut: { label: 'Haut & Ausschlag', color: 'rose' },
  kinderkrankheit: { label: 'Klassische Kinderkrankheiten', color: 'apricot' },
  allgemein: { label: 'Allgemein & Säuglinge', color: 'sand' }
};

const AGE_GROUPS = {
  saeugling: 'Säugling (0–1 J.)',
  kleinkind: 'Kleinkind (1–3 J.)',
  kita: 'Kita-Kind (3–6 J.)',
  schulkind: 'Schulkind (6+ J.)'
};

const SRC = {
  kgi: { label: 'BZgA – kindergesundheit-info.de: Das kranke Kind', url: 'https://www.kindergesundheit-info.de/themen/krankes-kind/' },
  gi: (slug, title) => ({ label: `IQWiG – gesundheitsinformation.de: ${title}`, url: `https://www.gesundheitsinformation.de/${slug}.html` }),
  nhs: (slug, title) => ({ label: `NHS (englisch): ${title}`, url: `https://www.nhs.uk/conditions/${slug}/` }),
  ifs: (path, title) => ({ label: `BZgA – infektionsschutz.de: ${title}`, url: `https://www.infektionsschutz.de/infektionen/erregersteckbriefe/${path}/` })
};

const DISEASES = [
  {
    id: 'fieber',
    name: 'Fieber bei Kindern',
    aliases: ['erhöhte Temperatur', 'Temperatur', 'heiß'],
    emoji: '🌡️',
    category: 'allgemein',
    ages: ['saeugling', 'kleinkind', 'kita', 'schulkind'],
    contagious: null,
    summary: 'Fieber ist keine Krankheit, sondern eine sinnvolle Abwehrreaktion des Körpers – meist auf harmlose Virusinfekte. Entscheidend ist weniger die Höhe der Temperatur als das Allgemeinbefinden deines Kindes.',
    symptoms: ['fieber', 'muedigkeit', 'appetitlosigkeit', 'unruhe', 'trinkschwaeche'],
    signs: [
      'Erhöhte Temperatur: etwa 37,6–38,4 °C; Fieber: ab etwa 38,5 °C (im Po gemessen)',
      'Heiße Stirn, glänzende Augen, gerötete Wangen',
      'Kinder sind oft müde, quengelig und haben wenig Hunger',
      'Kalte Hände und Füße bei steigendem Fieber, Schwitzen bei sinkendem'
    ],
    causes: 'Meist virale Infekte der Atemwege oder des Magen-Darm-Trakts, seltener bakterielle Infektionen. Auch nach Impfungen kann kurzzeitig Fieber auftreten.',
    duration: 'Bei einfachen Infekten meist 1–3 Tage.',
    care: [
      'Viel zu trinken anbieten – Wasser, ungesüßter Tee, Muttermilch oder Fläschchen',
      'Leichte Kleidung, nicht zusätzlich warm einpacken',
      'Ruhe erlauben, Kind nicht zum Essen zwingen',
      'Fiebersenkende Mittel sind nicht zwingend nötig – sie dienen vor allem dem Wohlbefinden',
      'Wadenwickel nur bei warmen Beinen und wenn das Kind sie mag'
    ],
    treatment: 'Wenn das Kind sich sehr unwohl fühlt, können Paracetamol oder Ibuprofen helfen – immer nach Körpergewicht dosiert und nach Rücksprache mit Kinderarztpraxis oder Apotheke. Ibuprofen ist je nach Präparat erst ab einem bestimmten Alter bzw. Gewicht zugelassen. Kinder sollten keine Acetylsalicylsäure (ASS/Aspirin) bekommen.',
    doctor: [
      'Säuglinge unter 3 Monaten mit 38 °C oder mehr – immer sofort',
      'Fieber länger als 3 Tage oder über 40 °C',
      'Das Kind trinkt kaum, hat deutlich weniger nasse Windeln',
      'Das Kind wirkt sehr krank, auch wenn das Fieber gesunken ist',
      'Neue Beschwerden wie Ohrenschmerzen, Ausschlag oder Schmerzen beim Wasserlassen'
    ],
    emergency: [
      'Das Kind ist kaum erweckbar, apathisch oder verwirrt',
      'Atemnot, bläuliche Lippen',
      'Krampfanfall',
      'Punktförmige, dunkelrote Flecken, die beim Drücken mit einem Glas nicht verblassen',
      'Steifer Nacken, starke Kopfschmerzen, sehr berührungsempfindlich'
    ],
    kita: 'Fieberfrei und fit sein – in der Regel mindestens 24 Stunden ohne fiebersenkende Mittel fieberfrei.',
    prevention: 'Gründliches Händewaschen und die empfohlenen Impfungen schützen vor vielen fieberhaften Infekten.',
    sources: [SRC.gi('fieber-bei-kindern', 'Fieber bei Kindern'), SRC.kgi, SRC.nhs('fever-in-children', 'Fever in children')]
  },
  {
    id: 'erkaeltung',
    name: 'Erkältung',
    aliases: ['grippaler Infekt', 'Schnupfen', 'Infekt der oberen Atemwege'],
    emoji: '🤧',
    category: 'atemwege',
    ages: ['saeugling', 'kleinkind', 'kita', 'schulkind'],
    contagious: true,
    summary: 'Kleinkinder haben bis zu 10 Erkältungen im Jahr – das ist normal und trainiert das Immunsystem. Meist sind Viren die Ursache und die Beschwerden klingen von allein ab.',
    symptoms: ['schnupfen', 'husten', 'halsschmerzen', 'fieber', 'muedigkeit', 'appetitlosigkeit', 'heiserkeit'],
    signs: [
      'Laufende oder verstopfte Nase, Niesen',
      'Halskratzen, Husten',
      'Leichtes Fieber, Müdigkeit',
      'Säuglinge trinken schlechter, weil die Nase zu ist'
    ],
    causes: 'Über 200 verschiedene Viren (z. B. Rhinoviren). Übertragung durch Tröpfchen und über die Hände.',
    duration: 'Meist 7–10 Tage, Husten kann bis zu 3 Wochen bleiben.',
    care: [
      'Viel trinken lassen',
      'Kochsalz-Nasentropfen oder -spray befreien die Nase, besonders vor dem Trinken und Schlafen',
      'Raumluft nicht zu trocken und nicht zu warm halten',
      'Kopfende leicht erhöht lagern (bei Babys nur unter der Matratze, keine Kissen im Bett)',
      'Honig kann Husten lindern – aber erst ab dem 1. Geburtstag'
    ],
    treatment: 'Gegen die Viren selbst gibt es keine Medikamente. Antibiotika helfen bei Erkältungen nicht. Abschwellende Nasentropfen nur kurz (wenige Tage) und in kindgerechter Dosierung nach Rücksprache.',
    doctor: [
      'Säuglinge unter 3 Monaten mit Fieber',
      'Fieber länger als 3 Tage',
      'Ohrenschmerzen oder Ausfluss aus dem Ohr',
      'Das Kind trinkt deutlich zu wenig',
      'Beschwerden werden nach einigen Tagen wieder schlimmer'
    ],
    emergency: ['Schwere oder sehr schnelle Atmung, Einziehungen zwischen den Rippen', 'Bläuliche Lippen', 'Das Kind ist kaum ansprechbar'],
    kita: 'Bei gutem Allgemeinbefinden und ohne Fieber ist der Besuch meist möglich – Schnupfen allein ist in der Regel kein Ausschlussgrund.',
    prevention: 'Händewaschen, in die Armbeuge niesen, Spielzeug regelmäßig reinigen.',
    sources: [SRC.gi('erkaeltung', 'Erkältung'), SRC.kgi, SRC.nhs('common-cold', 'Common cold')]
  },
  {
    id: 'mittelohrentzuendung',
    name: 'Mittelohrentzündung',
    aliases: ['Otitis media', 'Ohrenentzündung', 'Ohrenschmerzen'],
    emoji: '👂',
    category: 'atemwege',
    ages: ['saeugling', 'kleinkind', 'kita'],
    contagious: false,
    summary: 'Eine der häufigsten Erkrankungen im Kleinkindalter, oft im Anschluss an eine Erkältung. Sie heilt in den meisten Fällen innerhalb weniger Tage von allein aus.',
    symptoms: ['ohrenschmerzen', 'fieber', 'unruhe', 'schnupfen', 'appetitlosigkeit'],
    signs: [
      'Plötzliche, oft starke Ohrenschmerzen – häufig nachts',
      'Babys greifen sich ans Ohr, weinen viel, schlafen schlecht',
      'Fieber, eventuell vorübergehend schlechteres Hören',
      'Manchmal Ausfluss aus dem Ohr, wenn das Trommelfell einreißt (die Schmerzen lassen dann oft nach)'
    ],
    causes: 'Erreger gelangen aus dem Nasen-Rachen-Raum über die Ohrtrompete ins Mittelohr. Bei Kindern ist diese Verbindung kurz und eng.',
    duration: 'Die Schmerzen lassen meist nach 2–3 Tagen deutlich nach.',
    care: [
      'Schmerzmittel (Paracetamol oder Ibuprofen) altersgerecht nach Rücksprache',
      'Nase mit Kochsalztropfen freihalten',
      'Viel trinken, Ruhe',
      'Keine Gegenstände oder Hausmittel ins Ohr einbringen'
    ],
    treatment: 'Häufig wird zunächst abgewartet und nur gegen Schmerzen behandelt. Bei Kindern unter 6 Monaten, beidseitiger Entzündung bei Kleinkindern, Ausfluss oder anhaltenden Beschwerden verschreiben Ärztinnen und Ärzte oft ein Antibiotikum.',
    doctor: [
      'Ohrenschmerzen bei Kindern unter 2 Jahren',
      'Beschwerden bessern sich nach 2–3 Tagen nicht',
      'Ausfluss aus dem Ohr',
      'Hohes Fieber oder das Kind wirkt sehr krank'
    ],
    emergency: ['Schmerzhafte Schwellung oder Rötung hinter dem Ohr, abstehende Ohrmuschel', 'Steifer Nacken, starke Kopfschmerzen, Benommenheit'],
    kita: 'Nicht ansteckend. Wieder in die Kita, wenn das Kind fieberfrei ist und sich wohlfühlt.',
    prevention: 'Rauchfreie Umgebung, Stillen und die Pneumokokken-Impfung senken das Risiko.',
    sources: [SRC.gi('mittelohrentzuendung', 'Mittelohrentzündung'), SRC.nhs('ear-infections', 'Ear infections')]
  },
  {
    id: 'magen-darm',
    name: 'Magen-Darm-Infekt',
    aliases: ['Gastroenteritis', 'Brechdurchfall', 'Noro', 'Rota', 'Magen-Darm-Grippe'],
    emoji: '🤢',
    category: 'bauch',
    ages: ['saeugling', 'kleinkind', 'kita', 'schulkind'],
    contagious: true,
    summary: 'Plötzliches Erbrechen und Durchfall, meist durch Viren wie Noro- oder Rotaviren. Das Wichtigste ist, den Flüssigkeitsverlust auszugleichen – kleine Kinder trocknen schneller aus.',
    symptoms: ['erbrechen', 'durchfall', 'bauchschmerzen', 'fieber', 'appetitlosigkeit', 'muedigkeit'],
    signs: [
      'Plötzliches Erbrechen, oft zuerst',
      'Wässriger Durchfall',
      'Bauchkrämpfe, manchmal Fieber',
      'Zeichen von Flüssigkeitsmangel: trockener Mund, wenig/keine Tränen, wenig nasse Windeln'
    ],
    causes: 'Meist Noro- oder Rotaviren, seltener Bakterien. Sehr ansteckend über Hände, Oberflächen und Lebensmittel.',
    duration: 'Erbrechen meist 1–2 Tage, Durchfall bis zu 5–7 Tage.',
    care: [
      'Trinklösung (orale Rehydratationslösung, ORL, aus der Apotheke) in kleinen Mengen: alle paar Minuten einen Teelöffel oder Schluck',
      'Gestillte Kinder weiter stillen – gern häufiger',
      'Cola, Saft und Salzstangen sind nicht geeignet – sie gleichen den Verlust nicht richtig aus',
      'Sobald das Kind Hunger hat, normale, leichte Kost anbieten',
      'Sehr gründlich Hände waschen, eigene Handtücher, Toilette reinigen'
    ],
    treatment: 'Eine ursächliche Behandlung ist meist nicht nötig. Medikamente gegen Durchfall oder Erbrechen sind für kleine Kinder in der Regel nicht empfohlen – nur nach ärztlicher Rücksprache.',
    doctor: [
      'Säuglinge unter 6 Monaten mit Erbrechen oder Durchfall',
      'Das Kind behält trotz kleiner Schlucke nichts bei sich',
      'Durchfall länger als 5 Tage oder Erbrechen länger als 1–2 Tage',
      'Hohes Fieber, Blut oder Schleim im Stuhl'
    ],
    emergency: [
      'Zeichen starker Austrocknung: sehr trockene Windeln über 6–8 Stunden, eingesunkene Fontanelle, eingefallene Augen',
      'Das Kind ist schläfrig, schlapp oder kaum ansprechbar',
      'Grünliches oder blutiges Erbrechen',
      'Starke, anhaltende Bauchschmerzen, harter Bauch'
    ],
    kita: 'Frühestens 48 Stunden nach dem letzten Erbrechen bzw. Durchfall wieder in die Kita (Empfehlung bei infektiöser Gastroenteritis bei Kindern unter 6 Jahren).',
    prevention: 'Händewaschen nach jedem Toilettengang und Windelwechsel. Gegen Rotaviren gibt es eine Schluckimpfung ab 6 Wochen.',
    sources: [SRC.ifs('noroviren', 'Noroviren'), SRC.ifs('rotaviren', 'Rotaviren'), SRC.nhs('diarrhoea-and-vomiting', 'Diarrhoea and vomiting')]
  },
  {
    id: 'pseudokrupp',
    name: 'Pseudokrupp',
    aliases: ['Krupphusten', 'Laryngitis', 'bellender Husten'],
    emoji: '🦭',
    category: 'atemwege',
    ages: ['saeugling', 'kleinkind', 'kita'],
    contagious: true,
    summary: 'Eine virusbedingte Schwellung im Kehlkopfbereich. Typisch ist ein bellender Husten, oft nachts. Er klingt erschreckend, verläuft aber meistens mild.',
    symptoms: ['bellender-husten', 'heiserkeit', 'atemnot', 'schnupfen', 'fieber', 'unruhe'],
    signs: [
      'Bellender, „robbenartiger“ Husten',
      'Heisere Stimme',
      'Pfeifendes Geräusch beim Einatmen',
      'Beginnt häufig plötzlich in der Nacht, meist im Herbst und Winter'
    ],
    causes: 'Meist Parainfluenzaviren oder andere Erkältungsviren. Betrifft vor allem Kinder zwischen 6 Monaten und 3 Jahren.',
    duration: 'Meist 2–3 Tage, kann in den folgenden Nächten wiederkommen.',
    care: [
      'Ruhig bleiben und das Kind beruhigen – Aufregung verstärkt die Atemnot',
      'Kind aufrecht auf den Arm nehmen',
      'Kühle, frische Luft einatmen lassen: am offenen Fenster oder warm angezogen kurz nach draußen',
      'Etwas Kühles zu trinken anbieten'
    ],
    treatment: 'Ärztinnen und Ärzte verordnen meist ein Kortison-Präparat (z. B. als Zäpfchen oder Saft), das die Schwellung rasch lindert. Bei bekanntem Pseudokrupp kann ein Notfallmedikament zu Hause bereitliegen.',
    doctor: [
      'Beim ersten Pseudokrupp-Anfall immer ärztlich abklären lassen',
      'Beschwerden bessern sich nicht innerhalb von etwa 30 Minuten an der frischen Luft'
    ],
    emergency: [
      'Deutliche Atemnot, Einziehungen am Hals oder zwischen den Rippen',
      'Blasse oder bläuliche Haut / Lippen',
      'Das Kind sabbert stark, kann nicht schlucken, sitzt nach vorn gebeugt (Verdacht auf Kehldeckelentzündung)',
      'Unruhe, Angst, zunehmende Erschöpfung'
    ],
    kita: 'Wenn das Kind fieberfrei ist und sich wohlfühlt.',
    prevention: 'Allgemeine Hygiene; rauchfreie Umgebung.',
    sources: [SRC.gi('pseudokrupp', 'Pseudokrupp'), SRC.nhs('croup', 'Croup')]
  },
  {
    id: 'rsv-bronchiolitis',
    name: 'RSV & Bronchiolitis',
    aliases: ['RS-Virus', 'Respiratorisches Synzytial-Virus', 'Bronchiolitis'],
    emoji: '🫁',
    category: 'atemwege',
    ages: ['saeugling', 'kleinkind'],
    contagious: true,
    summary: 'RSV verursacht bei älteren Kindern meist nur eine Erkältung. Bei Säuglingen kann es die kleinsten Atemwege entzünden (Bronchiolitis) und das Atmen und Trinken erschweren.',
    symptoms: ['husten', 'schnupfen', 'atemnot', 'trinkschwaeche', 'fieber', 'unruhe'],
    signs: [
      'Beginnt wie eine Erkältung mit Schnupfen',
      'Nach 2–3 Tagen trockener, hartnäckiger Husten',
      'Schnelle oder angestrengte Atmung, manchmal pfeifend',
      'Säuglinge trinken schlecht'
    ],
    causes: 'Respiratorisches Synzytial-Virus, vor allem von Oktober bis März. Übertragung über Tröpfchen und Hände.',
    duration: 'Am schlimmsten meist an Tag 3–5, Husten kann 2–3 Wochen anhalten.',
    care: [
      'Nase mit Kochsalztropfen freihalten, besonders vor dem Trinken',
      'Häufiger kleinere Mengen anbieten',
      'Rauchfreie Umgebung',
      'Atmung und nasse Windeln im Blick behalten'
    ],
    treatment: 'Die Behandlung erfolgt unterstützend. Manche Säuglinge brauchen im Krankenhaus Sauerstoff oder Unterstützung beim Trinken.',
    doctor: [
      'Säuglinge, die nur noch etwa die Hälfte der üblichen Menge trinken',
      'Deutlich weniger nasse Windeln',
      'Fieber bei Säuglingen unter 3 Monaten',
      'Das Kind atmet sichtbar angestrengt'
    ],
    emergency: ['Atempausen', 'Bläuliche Lippen oder Zunge', 'Starke Einziehungen, Nasenflügeln, Stöhnen beim Ausatmen', 'Das Kind ist sehr schlapp'],
    kita: 'Wenn das Kind fieberfrei ist und gut atmet und trinkt.',
    prevention: 'Seit 2024 empfiehlt die STIKO für Neugeborene und Säuglinge in ihrer ersten RSV-Saison eine Prophylaxe mit einem Antikörper (Nirsevimab). Sprich deine Kinderarztpraxis darauf an.',
    sources: [SRC.nhs('bronchiolitis', 'Bronchiolitis'), SRC.kgi]
  },
  {
    id: 'hand-fuss-mund',
    name: 'Hand-Fuß-Mund-Krankheit',
    aliases: ['HFMK', 'Coxsackie', 'Hand-Fuß-Mund'],
    emoji: '🖐️',
    category: 'haut',
    ages: ['kleinkind', 'kita'],
    contagious: true,
    summary: 'Eine häufige, meist harmlose Viruserkrankung bei Kleinkindern mit schmerzhaften Bläschen im Mund und Ausschlag an Händen und Füßen.',
    symptoms: ['mund-blaeschen', 'ausschlag', 'blaeschen', 'fieber', 'halsschmerzen', 'appetitlosigkeit', 'trinkschwaeche'],
    signs: [
      'Zunächst leichtes Fieber, Halsschmerzen, wenig Appetit',
      'Schmerzhafte Bläschen und kleine Wunden im Mund',
      'Rote Flecken oder Bläschen an Handflächen, Fußsohlen, oft auch am Po',
      'Einige Wochen später können sich Finger- oder Fußnägel ablösen – harmlos, sie wachsen nach'
    ],
    causes: 'Enteroviren, z. B. Coxsackie-Viren. Übertragung über Speichel, Bläschenflüssigkeit und Stuhl.',
    duration: 'Etwa 7–10 Tage.',
    care: [
      'Kühle Getränke und weiche, kühle Speisen (z. B. Joghurt) – nichts Saures oder Scharfes',
      'Mit Strohhalm trinken kann helfen',
      'Schmerzmittel nach Rücksprache, besonders vor dem Essen',
      'Gründliches Händewaschen, besonders beim Windelwechsel'
    ],
    treatment: 'Es gibt keine spezielle Behandlung. Die Krankheit heilt von allein.',
    doctor: ['Das Kind trinkt zu wenig', 'Fieber länger als 3 Tage', 'Säuglinge unter 6 Monaten'],
    emergency: ['Zeichen von Austrocknung', 'Das Kind ist sehr schläfrig, verwirrt oder hat einen steifen Nacken'],
    kita: 'Es gibt kein gesetzliches Besuchsverbot. Ist das Kind fieberfrei und fit, ist der Besuch oft wieder möglich – frag nach den Regeln deiner Einrichtung.',
    prevention: 'Händewaschen; keine Becher und Löffel teilen.',
    sources: [SRC.ifs('hand-fuss-mund-krankheit', 'Hand-Fuß-Mund-Krankheit'), SRC.nhs('hand-foot-mouth-disease', 'Hand, foot and mouth disease')]
  },
  {
    id: 'windpocken',
    name: 'Windpocken',
    aliases: ['Varizellen', 'Wilde Blattern', 'Feuchtblattern'],
    emoji: '✨',
    category: 'kinderkrankheit',
    ages: ['kleinkind', 'kita', 'schulkind'],
    contagious: true,
    summary: 'Sehr ansteckende Viruserkrankung mit stark juckenden Bläschen am ganzen Körper. Dank Impfung heute seltener. Verläuft bei gesunden Kindern meist mild.',
    symptoms: ['blaeschen', 'juckreiz', 'ausschlag', 'fieber', 'muedigkeit', 'kopfschmerzen'],
    signs: [
      'Leichtes Fieber und Unwohlsein',
      'Rote Flecken, die sich zu juckenden Bläschen entwickeln und dann verkrusten',
      'Neue Bläschen kommen in Schüben – Flecken, Bläschen und Krusten gleichzeitig („Sternenhimmel“)',
      'Auch auf der Kopfhaut und an den Schleimhäuten'
    ],
    causes: 'Varizella-Zoster-Virus. Übertragung über die Luft („mit dem Wind“) und Kontakt mit Bläscheninhalt. Ansteckend etwa 1–2 Tage vor dem Ausschlag, bis alle Bläschen verkrustet sind (meist 5–7 Tage).',
    duration: 'Etwa 1–2 Wochen. Inkubationszeit 8–28 Tage, meist 14–16 Tage.',
    care: [
      'Fingernägel kurz schneiden, nachts evtl. Baumwollhandschuhe – Kratzen kann Narben verursachen',
      'Lockere Baumwollkleidung, nicht zu warm',
      'Kühlende, juckreizstillende Lotionen aus der Apotheke',
      'Viel trinken'
    ],
    treatment: 'Gegen Fieber und Schmerzen wird bei Windpocken häufig Paracetamol empfohlen; Ibuprofen sollte nur nach ärztlicher Rücksprache gegeben werden, da es mit Hautkomplikationen in Verbindung gebracht wird. Kein ASS. Bei Risikopersonen kann ein Virusmittel verordnet werden.',
    doctor: [
      'Säuglinge, Kinder mit geschwächtem Immunsystem oder Neurodermitis',
      'Bläschen sind stark gerötet, geschwollen, schmerzhaft oder eitrig',
      'Fieber steigt nach einigen Tagen erneut an',
      'Kontakt zu Schwangeren, die nicht immun sind – sie sollten ihre Ärztin informieren'
    ],
    emergency: ['Atemnot', 'Starke Kopfschmerzen, steifer Nacken, Gangunsicherheit oder Benommenheit', 'Ausgedehnte, sich schnell ausbreitende Hautrötung'],
    kita: 'Besuchsverbot nach Infektionsschutzgesetz, bis keine Ansteckung mehr besteht (alle Bläschen verkrustet). Die Kita muss informiert werden. Vor dem Arztbesuch anrufen, damit andere im Wartezimmer geschützt werden.',
    prevention: 'Die STIKO empfiehlt zwei Impfungen, im Alter von 11 und 15 Monaten (meist als Kombination mit MMR).',
    sources: [SRC.gi('windpocken', 'Windpocken'), SRC.ifs('windpocken-/-guertelrose', 'Windpocken'), SRC.nhs('chickenpox', 'Chickenpox')]
  },
  {
    id: 'dreitagefieber',
    name: 'Drei-Tage-Fieber',
    aliases: ['Exanthema subitum', 'Roseola infantum', 'Dreitagefieber'],
    emoji: '🌸',
    category: 'kinderkrankheit',
    ages: ['saeugling', 'kleinkind'],
    contagious: true,
    summary: 'Typisch für Babys und Kleinkinder: drei Tage hohes Fieber, danach – wenn das Fieber fällt – ein blassroter Ausschlag. Das Kind ist dann meist schon wieder munter.',
    symptoms: ['fieber', 'ausschlag', 'unruhe', 'appetitlosigkeit', 'lymphknoten'],
    signs: [
      'Plötzlich hohes Fieber (oft 39–40 °C) für etwa 3 Tage',
      'Nach dem Fieberabfall kleinfleckiger, blassroter Ausschlag vor allem am Rumpf',
      'Ausschlag juckt nicht und verschwindet nach 1–2 Tagen',
      'Teilweise geschwollene Lymphknoten am Hals'
    ],
    causes: 'Humane Herpesviren 6 und 7. Betrifft meist Kinder zwischen 6 Monaten und 3 Jahren.',
    duration: 'Etwa eine Woche insgesamt.',
    care: ['Viel trinken lassen', 'Fiebersenkende Mittel bei Unwohlsein nach Rücksprache', 'Ruhe'],
    treatment: 'Keine spezielle Behandlung nötig.',
    doctor: ['Säuglinge unter 3 Monaten mit Fieber', 'Fieber länger als 3 Tage', 'Das Kind trinkt schlecht oder wirkt sehr krank'],
    emergency: ['Fieberkrampf, besonders wenn er länger als 5 Minuten dauert', 'Das Kind ist kaum ansprechbar'],
    kita: 'Wenn das Kind fieberfrei ist und sich wohlfühlt. Sobald der Ausschlag da ist, ist es kaum noch ansteckend.',
    prevention: 'Keine Impfung verfügbar. Fast alle Kinder machen die Infektion durch.',
    sources: [SRC.nhs('roseola', 'Roseola'), SRC.kgi]
  },
  {
    id: 'scharlach',
    name: 'Scharlach',
    aliases: ['Streptokokken-Angina', 'Scarlatina'],
    emoji: '🍓',
    category: 'kinderkrankheit',
    ages: ['kita', 'schulkind'],
    contagious: true,
    summary: 'Eine bakterielle Infektion mit Halsschmerzen, Fieber, Himbeerzunge und typischem Ausschlag. Sie wird mit Antibiotika behandelt und ist dann schnell nicht mehr ansteckend.',
    symptoms: ['halsschmerzen', 'fieber', 'himbeerzunge', 'ausschlag', 'kopfschmerzen', 'erbrechen', 'bauchschmerzen', 'lymphknoten'],
    signs: [
      'Plötzlich Fieber, starke Halsschmerzen, Schluckbeschwerden',
      'Teilweise Bauchschmerzen und Erbrechen',
      'Feinfleckiger Ausschlag, fühlt sich samtig an – beginnt oft in den Leisten und Achseln',
      'Blasse Zone um den Mund, „Himbeerzunge“ nach einigen Tagen',
      'Später kann sich die Haut an Händen und Füßen schälen'
    ],
    causes: 'Streptokokken der Gruppe A. Übertragung über Tröpfchen. Man kann mehrmals erkranken.',
    duration: 'Mit Antibiotikum bessern sich die Beschwerden meist innerhalb von 1–2 Tagen.',
    care: ['Weiche, kühle Speisen, viel trinken', 'Ruhe', 'Antibiotikum unbedingt so lange geben wie verordnet'],
    treatment: 'Ärztliche Diagnose mit Rachenabstrich. Behandlung meist mit Penicillin oder einem anderen Antibiotikum.',
    doctor: ['Bei Verdacht auf Scharlach immer zur Kinderarztpraxis', 'Einige Wochen später: Gelenkschmerzen, Schwellungen, dunkler Urin'],
    emergency: ['Das Kind kann nicht mehr schlucken oder den Mund kaum öffnen', 'Atemnot', 'Sehr schlechter Allgemeinzustand'],
    kita: 'Besuchsverbot nach Infektionsschutzgesetz; bei Antibiotika-Behandlung und ohne Krankheitszeichen meist ab dem 2. Behandlungstag wieder möglich.',
    prevention: 'Keine Impfung. Händewaschen, Husten-Etikette.',
    sources: [SRC.gi('scharlach', 'Scharlach'), SRC.ifs('scharlach', 'Scharlach'), SRC.nhs('scarlet-fever', 'Scarlet fever')]
  },
  {
    id: 'masern',
    name: 'Masern',
    aliases: ['Morbilli'],
    emoji: '🔴',
    category: 'kinderkrankheit',
    ages: ['saeugling', 'kleinkind', 'kita', 'schulkind'],
    contagious: true,
    summary: 'Eine der ansteckendsten Krankheiten überhaupt – und keineswegs harmlos. Komplikationen wie Lungen- oder Gehirnentzündung sind möglich. Die Impfung schützt sehr zuverlässig.',
    symptoms: ['fieber', 'husten', 'schnupfen', 'rote-augen', 'ausschlag', 'muedigkeit'],
    signs: [
      'Zuerst Fieber, Schnupfen, Husten, gerötete, lichtempfindliche Augen',
      'Weißliche Flecken an der Wangenschleimhaut',
      'Nach 3–7 Tagen großfleckiger, rotbrauner Ausschlag – beginnt hinter den Ohren und im Gesicht',
      'Erneuter Fieberanstieg mit dem Ausschlag'
    ],
    causes: 'Masernvirus, Übertragung über die Luft. Ansteckend etwa 4 Tage vor bis 4 Tage nach Beginn des Ausschlags.',
    duration: 'Etwa 2 Wochen, Erschöpfung kann länger anhalten.',
    care: ['Ruhe, abgedunkelter Raum bei Lichtempfindlichkeit', 'Viel trinken', 'Fiebersenkende Mittel nach Rücksprache'],
    treatment: 'Keine ursächliche Therapie; Behandlung der Beschwerden und Komplikationen.',
    doctor: ['Bei jedem Verdacht auf Masern – vorher anrufen, nicht unangemeldet ins Wartezimmer!'],
    emergency: ['Atemnot', 'Krampfanfall, Bewusstseinsstörung, starke Kopfschmerzen', 'Das Kind trinkt nicht mehr'],
    kita: 'Meldepflichtig, Besuchsverbot nach Infektionsschutzgesetz. Für den Kita-Besuch ist ein Masern-Impfnachweis gesetzlich vorgeschrieben.',
    prevention: 'Zwei Impfungen (MMR) im Alter von 11 und 15 Monaten.',
    sources: [SRC.gi('masern', 'Masern'), SRC.ifs('masern', 'Masern'), SRC.nhs('measles', 'Measles')]
  },
  {
    id: 'mumps',
    name: 'Mumps',
    aliases: ['Ziegenpeter', 'Parotitis'],
    emoji: '🐹',
    category: 'kinderkrankheit',
    ages: ['kita', 'schulkind'],
    contagious: true,
    summary: 'Eine Viruserkrankung mit typisch geschwollenen „Hamsterbacken“ durch Entzündung der Ohrspeicheldrüse. Dank Impfung selten geworden.',
    symptoms: ['schwellung-wange', 'fieber', 'kopfschmerzen', 'appetitlosigkeit', 'muedigkeit'],
    signs: ['Schmerzhafte Schwellung vor und unter dem Ohr, ein- oder beidseitig', 'Schmerzen beim Kauen', 'Fieber, Kopfschmerzen, Abgeschlagenheit'],
    causes: 'Mumpsvirus, Übertragung über Tröpfchen und Speichel.',
    duration: 'Schwellung etwa 3–8 Tage.',
    care: ['Weiche Kost, viel trinken – keine sauren Getränke', 'Kühle oder warme Umschläge, je nachdem, was guttut', 'Schmerzmittel nach Rücksprache'],
    treatment: 'Keine ursächliche Therapie.',
    doctor: ['Bei Verdacht auf Mumps (vorher anrufen)', 'Bauchschmerzen, Hodenschmerzen oder -schwellung'],
    emergency: ['Starke Kopfschmerzen, steifer Nacken, Benommenheit'],
    kita: 'Meldepflichtig, Besuchsverbot nach Infektionsschutzgesetz.',
    prevention: 'MMR-Impfung mit 11 und 15 Monaten.',
    sources: [SRC.gi('mumps', 'Mumps'), SRC.ifs('mumps', 'Mumps'), SRC.nhs('mumps', 'Mumps')]
  },
  {
    id: 'roeteln',
    name: 'Röteln',
    aliases: ['Rubella', 'Rubeola'],
    emoji: '🎀',
    category: 'kinderkrankheit',
    ages: ['kleinkind', 'kita', 'schulkind'],
    contagious: true,
    summary: 'Bei Kindern meist milde Viruserkrankung mit kleinfleckigem Ausschlag. Gefährlich ist sie vor allem für ungeborene Kinder – deshalb ist die Impfung so wichtig.',
    symptoms: ['ausschlag', 'lymphknoten', 'fieber', 'rote-augen', 'schnupfen'],
    signs: ['Hellroter, kleinfleckiger Ausschlag, beginnt im Gesicht', 'Geschwollene Lymphknoten im Nacken und hinter den Ohren', 'Leichtes Fieber'],
    causes: 'Rötelnvirus, Übertragung über Tröpfchen.',
    duration: 'Ausschlag 1–3 Tage.',
    care: ['Ruhe, viel trinken', 'Kontakt zu Schwangeren vermeiden'],
    treatment: 'Keine ursächliche Therapie nötig.',
    doctor: ['Bei Verdacht (vorher anrufen)', 'Wenn Kontakt zu einer Schwangeren bestand – sie sollte sich ärztlich beraten lassen'],
    emergency: ['Starke Kopfschmerzen, Benommenheit, Krampfanfall'],
    kita: 'Meldepflichtig. Die Kita informieren und das Vorgehen mit Kinderarztpraxis und Gesundheitsamt abstimmen.',
    prevention: 'MMR-Impfung mit 11 und 15 Monaten.',
    sources: [SRC.gi('roeteln', 'Röteln'), SRC.ifs('roeteln', 'Röteln'), SRC.nhs('rubella', 'Rubella')]
  },
  {
    id: 'ringelroeteln',
    name: 'Ringelröteln',
    aliases: ['Erythema infectiosum', 'Parvovirus B19', 'Fünfte Krankheit'],
    emoji: '🌹',
    category: 'kinderkrankheit',
    ages: ['kita', 'schulkind'],
    contagious: true,
    summary: 'Harmlose Viruserkrankung mit auffällig roten „Ohrfeigen-Wangen“ und girlandenförmigem Ausschlag. Wenn der Ausschlag da ist, ist das Kind kaum noch ansteckend.',
    symptoms: ['rote-wangen', 'ausschlag', 'juckreiz', 'fieber', 'schnupfen', 'kopfschmerzen'],
    signs: ['Zuerst evtl. leichte Erkältungszeichen', 'Knallrote Wangen, Mund-Kinn-Partie bleibt blass', 'Danach ring- oder girlandenförmiger Ausschlag an Armen, Beinen, Po – kann jucken und kommt und geht über Wochen'],
    causes: 'Parvovirus B19, Übertragung über Tröpfchen.',
    duration: 'Ausschlag kann 1–3 Wochen wiederkehren, z. B. bei Wärme oder Sonne.',
    care: ['Kühle Lotion bei Juckreiz', 'Keine besondere Schonung nötig, wenn das Kind fit ist'],
    treatment: 'Keine spezielle Behandlung.',
    doctor: ['Wenn das Kind eine Blutkrankheit oder ein geschwächtes Immunsystem hat', 'Kontakt zu Schwangeren – sie sollten ihre Ärztin informieren'],
    emergency: ['Sehr blasse Haut, Herzrasen, Schwäche (bei Kindern mit Blutkrankheiten)'],
    kita: 'Mit Ausschlag ist das Kind meist nicht mehr ansteckend und darf in der Regel in die Kita.',
    prevention: 'Keine Impfung; Händewaschen.',
    sources: [SRC.ifs('ringelroeteln', 'Ringelröteln'), SRC.nhs('slapped-cheek-syndrome', 'Slapped cheek syndrome')]
  },
  {
    id: 'bindehautentzuendung',
    name: 'Bindehautentzündung',
    aliases: ['Konjunktivitis', 'rotes Auge', 'Augenentzündung'],
    emoji: '👁️',
    category: 'haut',
    ages: ['saeugling', 'kleinkind', 'kita', 'schulkind'],
    contagious: true,
    summary: 'Gerötete, tränende oder verklebte Augen – häufig durch Viren oder Bakterien, manchmal durch Allergien. Meist harmlos, aber oft ansteckend.',
    symptoms: ['rote-augen', 'augen-verklebt', 'juckreiz', 'schnupfen'],
    signs: ['Gerötetes Augenweiß', 'Tränende Augen, Fremdkörpergefühl', 'Gelblicher Ausfluss, morgens verklebte Lider (eher bakteriell)', 'Oft ein Auge zuerst, dann beide'],
    causes: 'Viren, Bakterien oder Allergien. Infektiöse Formen werden über Hände und Handtücher übertragen.',
    duration: 'Meist 1–2 Wochen.',
    care: ['Augen von außen nach innen mit abgekochtem, abgekühltem Wasser und Wattepads reinigen – für jedes Auge ein neues Pad', 'Eigene Handtücher und Waschlappen', 'Häufig Hände waschen'],
    treatment: 'Bakterielle Entzündungen können mit antibiotischen Augentropfen behandelt werden, heilen aber oft auch von allein. Bei Allergie helfen antiallergische Tropfen.',
    doctor: ['Neugeborene mit geröteten oder eitrigen Augen – immer', 'Starke Schmerzen, Lichtempfindlichkeit, Sehstörungen', 'Keine Besserung nach einigen Tagen'],
    emergency: ['Schwellung und Rötung der Lider mit Fieber', 'Verletzung oder Fremdkörper im Auge'],
    kita: 'Regelungen sind unterschiedlich – viele Einrichtungen bitten bei eitriger Bindehautentzündung um ärztliche Abklärung.',
    prevention: 'Händewaschen, Handtücher nicht teilen.',
    sources: [SRC.gi('bindehautentzuendung', 'Bindehautentzündung'), SRC.nhs('conjunctivitis', 'Conjunctivitis')]
  },
  {
    id: 'kopflaeuse',
    name: 'Kopfläuse',
    aliases: ['Läuse', 'Pediculosis'],
    emoji: '🪮',
    category: 'haut',
    ages: ['kita', 'schulkind'],
    contagious: true,
    summary: 'Läuse sind lästig, aber kein Zeichen mangelnder Hygiene. Mit konsequenter Behandlung und Auskämmen ist man sie zuverlässig wieder los.',
    symptoms: ['kopfjucken', 'juckreiz'],
    signs: ['Juckende Kopfhaut, Kratzspuren besonders hinter den Ohren und im Nacken', 'Nissen: kleine, fest am Haar klebende Eihüllen nah an der Kopfhaut', 'Lebende Läuse beim nassen Auskämmen'],
    causes: 'Übertragung fast nur durch direkten Haar-zu-Haar-Kontakt, z. B. beim Spielen.',
    duration: 'Mit korrekter Behandlung nach etwa 2–3 Wochen erledigt.',
    care: [
      'Tag 1: Behandlung mit einem Läusemittel aus der Apotheke und nasses Auskämmen mit Läusekamm',
      'Tag 5: Nass auskämmen',
      'Tag 8, 9 oder 10: Zweite Behandlung mit dem Läusemittel',
      'Tag 13: Nass auskämmen',
      'Tag 17: Letzte Kontrolle durch nasses Auskämmen',
      'Kämme und Bürsten reinigen; großer Putzaufwand in der Wohnung ist nicht nötig'
    ],
    treatment: 'Läusemittel aus der Apotheke, genau nach Gebrauchsanweisung. Für Säuglinge und Kleinkinder vorher in der Apotheke oder Praxis beraten lassen.',
    doctor: ['Bei Säuglingen', 'Entzündete, nässende Kopfhaut', 'Wenn die Läuse trotz korrekter Behandlung wiederkommen'],
    emergency: [],
    kita: 'Eltern müssen die Kita informieren. Nach der ersten korrekten Behandlung darf das Kind in der Regel wieder hin – manche Einrichtungen verlangen eine Bestätigung.',
    prevention: 'Regelmäßig nachschauen, wenn es Läuse in Kita oder Schule gibt. Lange Haare zusammenbinden.',
    sources: [SRC.gi('kopflaeuse', 'Kopfläuse'), SRC.nhs('head-lice-and-nits', 'Head lice and nits')]
  },
  {
    id: 'neurodermitis',
    name: 'Neurodermitis',
    aliases: ['atopisches Ekzem', 'atopische Dermatitis', 'Milchschorf'],
    emoji: '🧴',
    category: 'haut',
    ages: ['saeugling', 'kleinkind', 'kita', 'schulkind'],
    contagious: false,
    summary: 'Eine chronische, nicht ansteckende Hauterkrankung mit trockener, juckender Haut, die in Schüben verläuft. Bei vielen Kindern bessert sie sich mit dem Älterwerden deutlich.',
    symptoms: ['trockene-haut', 'juckreiz', 'ausschlag', 'unruhe', 'rote-wangen'],
    signs: ['Sehr trockene, raue Haut', 'Gerötete, juckende Ekzeme – bei Babys oft im Gesicht und an der Kopfhaut, später in Arm- und Kniebeugen', 'Unruhe und schlechter Schlaf durch Juckreiz'],
    causes: 'Veranlagung (Familie mit Allergien, Asthma) und eine gestörte Hautbarriere. Auslöser können z. B. Schwitzen, Wolle, Infekte oder Stress sein.',
    duration: 'Chronisch, verläuft in Schüben.',
    care: ['Tägliche rückfettende Basispflege – auch in beschwerdefreien Zeiten', 'Kurz und lauwarm baden, Haut danach sanft abtupfen und eincremen', 'Weiche Baumwollkleidung, Fingernägel kurz', 'Persönliche Auslöser beobachten (z. B. mit einem Tagebuch)'],
    treatment: 'Bei Schüben verordnen Ärztinnen und Ärzte meist entzündungshemmende Cremes (z. B. kortisonhaltig), die richtig angewendet sicher sind. Nahrungsmittel nicht auf eigene Faust weglassen.',
    doctor: ['Bei Verdacht auf Neurodermitis', 'Der Juckreiz stört den Schlaf deutlich', 'Nässende, krustige oder eitrige Stellen'],
    emergency: ['Plötzlich viele schmerzhafte, ausgestanzte Bläschen mit Fieber (mögliche Herpes-Infektion der Haut)'],
    kita: 'Nicht ansteckend – kein Grund, zu Hause zu bleiben.',
    prevention: 'Bei Babys mit hohem Risiko kann regelmäßiges Eincremen helfen; Stillen wird empfohlen.',
    sources: [SRC.gi('neurodermitis', 'Neurodermitis'), SRC.nhs('atopic-eczema', 'Atopic eczema')]
  },
  {
    id: 'fieberkrampf',
    name: 'Fieberkrampf',
    aliases: ['Fieberkrämpfe', 'Krampfanfall bei Fieber'],
    emoji: '⚡',
    category: 'allgemein',
    ages: ['saeugling', 'kleinkind', 'kita'],
    contagious: false,
    summary: 'Ein Krampfanfall bei Fieber – erschreckend für Eltern, aber meist harmlos und ohne bleibende Folgen. Betroffen sind etwa 2–5 von 100 Kindern zwischen 6 Monaten und 5 Jahren.',
    symptoms: ['krampf', 'fieber'],
    signs: ['Das Kind wird plötzlich bewusstlos, steif oder zuckt rhythmisch mit Armen und Beinen', 'Verdrehte Augen, blasse oder bläuliche Lippen', 'Danach meist müde und schläfrig'],
    causes: 'Ein schneller Fieberanstieg bei einem Infekt. Es besteht oft eine familiäre Veranlagung.',
    duration: 'Meist unter 5 Minuten, selten bis 15 Minuten.',
    care: [
      'Ruhe bewahren und auf die Uhr schauen',
      'Kind auf eine weiche Unterlage legen, Gegenstände wegräumen',
      'Nichts in den Mund stecken, nicht festhalten',
      'Nach dem Anfall in die stabile Seitenlage bringen',
      'Bei bekannter Neigung: verordnetes Notfallmedikament wie besprochen geben'
    ],
    treatment: 'Fiebersenkende Mittel verhindern Fieberkrämpfe nach heutigem Wissen nicht zuverlässig. Bei längeren Anfällen kann ein Notfallmedikament verordnet werden.',
    doctor: ['Nach jedem ersten Fieberkrampf ärztlich abklären lassen'],
    emergency: ['Krampf dauert länger als 5 Minuten – 112 rufen', 'Erster Krampfanfall überhaupt', 'Das Kind wacht nach dem Anfall nicht richtig auf, atmet schwer', 'Steifer Nacken, punktförmiger Ausschlag, Alter unter 6 Monaten'],
    kita: 'Wie bei Fieber: wenn das Kind fieberfrei und fit ist.',
    prevention: 'Nicht sicher vermeidbar. Ein Notfallplan mit der Kinderarztpraxis gibt Sicherheit.',
    sources: [SRC.kgi, SRC.nhs('febrile-seizures', 'Febrile seizures')]
  },
  {
    id: 'mundfaeule',
    name: 'Mundfäule',
    aliases: ['Stomatitis aphthosa', 'Gingivostomatitis herpetica', 'Herpes im Mund'],
    emoji: '👄',
    category: 'haut',
    ages: ['kleinkind', 'kita'],
    contagious: true,
    summary: 'Die erste Ansteckung mit Herpesviren verursacht bei Kleinkindern oft schmerzhafte Bläschen und Wunden im ganzen Mund. Das Hauptrisiko: Die Kinder trinken zu wenig.',
    symptoms: ['mund-blaeschen', 'fieber', 'sabbern', 'trinkschwaeche', 'appetitlosigkeit', 'lymphknoten', 'unruhe'],
    signs: ['Hohes Fieber', 'Viele schmerzhafte Bläschen und gelblich belegte Wunden an Zahnfleisch, Zunge, Lippen', 'Geschwollenes, leicht blutendes Zahnfleisch, Mundgeruch', 'Starkes Sabbern, Essens- und Trinkverweigerung'],
    causes: 'Herpes-simplex-Virus Typ 1, Übertragung über Speichel – z. B. durch Küsse von Erwachsenen mit Lippenherpes.',
    duration: 'Etwa 7–14 Tage.',
    care: ['Kühle, milde Getränke und weiche, kühle Speisen anbieten', 'Schmerzmittel nach Rücksprache, besonders vor dem Trinken', 'Nichts Saures, Salziges oder Scharfes', 'Keine Küsse auf den Mund bei Lippenherpes in der Familie'],
    treatment: 'Ärztinnen und Ärzte können schmerzlindernde Mundgele oder in manchen Fällen ein Virusmittel (Aciclovir) verordnen – am besten früh im Verlauf.',
    doctor: ['Bei Verdacht auf Mundfäule', 'Das Kind trinkt kaum noch'],
    emergency: ['Zeichen der Austrocknung: kaum nasse Windeln, trockener Mund, schläfrig', 'Bläschen am Auge'],
    kita: 'Solange Bläschen bestehen und das Kind sabbert, sollte es zu Hause bleiben.',
    prevention: 'Kein Küssen von Kindern bei eigenem Lippenherpes.',
    sources: [SRC.gi('lippenherpes', 'Lippenherpes'), SRC.kgi]
  },
  {
    id: 'mandelentzuendung',
    name: 'Mandelentzündung',
    aliases: ['Tonsillitis', 'Angina', 'Halsentzündung'],
    emoji: '🍯',
    category: 'atemwege',
    ages: ['kita', 'schulkind'],
    contagious: true,
    summary: 'Halsschmerzen mit geröteten, geschwollenen Mandeln – meist durch Viren, seltener durch Bakterien (Streptokokken). Klingt in der Regel innerhalb einer Woche ab.',
    symptoms: ['halsschmerzen', 'fieber', 'lymphknoten', 'kopfschmerzen', 'appetitlosigkeit', 'bauchschmerzen'],
    signs: ['Halsschmerzen, Schluckbeschwerden', 'Gerötete, geschwollene Mandeln, evtl. mit Belägen', 'Fieber, geschwollene Lymphknoten am Hals', 'Jüngere Kinder klagen manchmal eher über Bauchschmerzen'],
    causes: 'Meist Viren, bei Kindern ab etwa 3 Jahren auch Streptokokken.',
    duration: 'Etwa 3–7 Tage.',
    care: ['Viel trinken, weiche und kühle Speisen', 'Schmerzmittel nach Rücksprache', 'Ältere Kinder: Lutschpastillen können lindern'],
    treatment: 'Bei Verdacht auf Streptokokken kann ein Schnelltest gemacht und ggf. ein Antibiotikum verordnet werden.',
    doctor: ['Hohes Fieber oder starke Beschwerden', 'Keine Besserung nach 3–4 Tagen', 'Ausschlag kommt hinzu'],
    emergency: ['Das Kind kann nicht mehr schlucken, sabbert stark', 'Kloßige Sprache und Mundöffnung kaum möglich', 'Atemnot'],
    kita: 'Wenn das Kind fieberfrei ist und sich wohlfühlt; bei Streptokokken frühestens 24 Stunden nach Beginn der Antibiotika-Gabe.',
    prevention: 'Händewaschen, keine Gläser teilen.',
    sources: [SRC.gi('mandelentzuendung', 'Mandelentzündung'), SRC.nhs('tonsillitis', 'Tonsillitis')]
  },
  {
    id: 'harnwegsinfekt',
    name: 'Harnwegsinfekt',
    aliases: ['Blasenentzündung', 'Zystitis', 'HWI'],
    emoji: '💧',
    category: 'bauch',
    ages: ['saeugling', 'kleinkind', 'kita', 'schulkind'],
    contagious: false,
    summary: 'Bakterien in Harnröhre und Blase – bei Babys oft nur mit Fieber und ohne typische Beschwerden. Muss ärztlich abgeklärt und meist mit Antibiotika behandelt werden.',
    symptoms: ['brennen-wasserlassen', 'fieber', 'bauchschmerzen', 'erbrechen', 'unruhe', 'trinkschwaeche'],
    signs: ['Brennen oder Schmerzen beim Wasserlassen', 'Häufiger Harndrang, plötzliches Einnässen', 'Übel riechender oder trüber Urin', 'Bei Babys oft nur Fieber, Trinkschwäche, Unruhe, Erbrechen'],
    causes: 'Meist Darmbakterien, die über die Harnröhre aufsteigen.',
    duration: 'Mit Behandlung bessert sich das Befinden meist in 1–2 Tagen.',
    care: ['Viel trinken', 'Toilettengang nicht aufschieben', 'Bei Mädchen von vorn nach hinten abwischen'],
    treatment: 'Urinuntersuchung in der Praxis, meist Antibiotikum. Bei Säuglingen und wiederkehrenden Infekten weitere Untersuchungen.',
    doctor: ['Bei Verdacht immer zur Kinderarztpraxis', 'Fieber ohne erkennbare Ursache bei Säuglingen'],
    emergency: ['Hohes Fieber mit Flankenschmerzen, Schüttelfrost, Erbrechen und sehr krankem Eindruck'],
    kita: 'Nicht ansteckend; wenn das Kind fieberfrei und fit ist.',
    prevention: 'Ausreichend trinken, regelmäßig zur Toilette.',
    sources: [SRC.nhs('urinary-tract-infections-utis', 'Urinary tract infections'), SRC.kgi]
  },
  {
    id: 'keuchhusten',
    name: 'Keuchhusten',
    aliases: ['Pertussis'],
    emoji: '😮‍💨',
    category: 'kinderkrankheit',
    ages: ['saeugling', 'kleinkind', 'kita', 'schulkind'],
    contagious: true,
    summary: 'Eine bakterielle Infektion mit wochenlangen, quälenden Hustenanfällen. Für junge Säuglinge kann sie lebensgefährlich sein – Impfungen schützen.',
    symptoms: ['hustenanfaelle', 'husten', 'schnupfen', 'erbrechen', 'atemnot'],
    signs: ['1–2 Wochen erkältungsähnlich', 'Dann heftige Hustenanfälle, oft nachts, mit hörbarem Einziehen der Luft („Keuchen“)', 'Hervorgewürgter Schleim, Erbrechen nach dem Husten', 'Säuglinge: oft kein typischer Husten, sondern Atemaussetzer'],
    causes: 'Bakterium Bordetella pertussis, Übertragung über Tröpfchen.',
    duration: 'Oft 6–10 Wochen („100-Tage-Husten“).',
    care: ['Ruhige Umgebung, häufige kleine Mahlzeiten', 'Bei Anfällen Kind aufsetzen und beruhigen', 'Kontakt zu Säuglingen und Schwangeren vermeiden'],
    treatment: 'Antibiotika verkürzen die Ansteckungszeit, besonders wenn sie früh gegeben werden. Säuglinge werden oft im Krankenhaus überwacht.',
    doctor: ['Husten länger als 2 Wochen oder anfallsartig', 'Erbrechen nach Hustenanfällen'],
    emergency: ['Atemaussetzer oder Blauwerden – besonders bei Säuglingen', 'Das Kind ist nach Anfällen erschöpft und kann nicht trinken'],
    kita: 'Meldepflichtig, Besuchsverbot nach Infektionsschutzgesetz; mit Antibiotikum frühestens nach 5 Tagen Behandlung wieder in die Kita.',
    prevention: 'Impfung im Rahmen der 6-fach-Impfung ab 2 Monaten. Die Impfung in der Schwangerschaft schützt Neugeborene. Auch Eltern und Geschwister sollten geimpft sein.',
    sources: [SRC.ifs('keuchhusten', 'Keuchhusten'), SRC.nhs('whooping-cough', 'Whooping cough')]
  },
  {
    id: 'windeldermatitis',
    name: 'Windeldermatitis',
    aliases: ['wunder Po', 'Windelausschlag', 'Windelsoor'],
    emoji: '🍑',
    category: 'haut',
    ages: ['saeugling', 'kleinkind'],
    contagious: false,
    summary: 'Ein wunder, geröteter Po ist bei Wickelkindern sehr häufig. Meist reichen Luft, häufiges Wickeln und eine Schutzcreme.',
    symptoms: ['windelbereich', 'ausschlag', 'unruhe', 'juckreiz'],
    signs: ['Rote, glänzende, teils nässende Haut im Windelbereich', 'Weinen beim Wickeln', 'Rote Pünktchen am Rand („Satelliten“) deuten auf eine Pilzinfektion hin'],
    causes: 'Feuchtigkeit, Reibung und Kontakt mit Urin und Stuhl – besonders bei Durchfall. Oft kommt ein Hefepilz (Candida) hinzu.',
    duration: 'Mit guter Pflege wenige Tage.',
    care: ['Häufig wickeln, so oft wie möglich ohne Windel strampeln lassen', 'Nur mit lauwarmem Wasser reinigen, sanft trocken tupfen', 'Zinkhaltige Schutzcreme dünn auftragen', 'Keine parfümierten Feuchttücher'],
    treatment: 'Bei Pilzbefall verordnen Ärztinnen und Ärzte eine pilzhemmende Creme.',
    doctor: ['Keine Besserung nach 3–4 Tagen', 'Pustel, Bläschen, offene Stellen', 'Verdacht auf Pilz (Satelliten-Pünktchen) oder weiße Beläge im Mund'],
    emergency: [],
    kita: 'Nicht ansteckend.',
    prevention: 'Häufiges Wickeln, Luft an die Haut lassen.',
    sources: [{ label: 'NHS (englisch): Nappy rash', url: 'https://www.nhs.uk/baby/caring-for-a-newborn/nappy-rash/' }, SRC.kgi]
  },
  {
    id: 'zahnen',
    name: 'Zahnen',
    aliases: ['Zahndurchbruch', 'erste Zähne'],
    emoji: '🦷',
    category: 'allgemein',
    ages: ['saeugling', 'kleinkind'],
    contagious: false,
    summary: 'Die ersten Zähne kommen meist zwischen dem 6. und 10. Lebensmonat. Viele Babys sind dabei unruhig – Zahnen verursacht aber kein hohes Fieber und keinen starken Durchfall.',
    symptoms: ['sabbern', 'unruhe', 'rote-wangen', 'appetitlosigkeit'],
    signs: ['Vermehrtes Sabbern, Kauen auf Fingern und Gegenständen', 'Gerötetes, geschwollenes Zahnfleisch', 'Gerötete Wange, Unruhe, schlechter Schlaf', 'Höchstens leicht erhöhte Temperatur'],
    causes: 'Der Zahn schiebt sich durch das Zahnfleisch.',
    duration: 'Wenige Tage pro Zahn.',
    care: ['Gekühlter (nicht gefrorener) Beißring', 'Zahnfleisch mit sauberem Finger sanft massieren', 'Viel Nähe und Trost', 'Ab dem ersten Zahn mit dem Zähneputzen beginnen'],
    treatment: 'Bei starken Beschwerden nach Rücksprache ein altersgerechtes Schmerzmittel. Von Bernsteinketten wird wegen Erstickungs- und Strangulationsgefahr abgeraten.',
    doctor: ['Fieber über 38,5 °C oder Durchfall – das hat dann meist eine andere Ursache'],
    emergency: [],
    kita: 'Kein Grund, zu Hause zu bleiben.',
    prevention: '—',
    sources: [{ label: 'NHS (englisch): Baby teething symptoms', url: 'https://www.nhs.uk/baby/babys-development/teething/baby-teething-symptoms/' }, SRC.kgi]
  },
  {
    id: 'saeuglingskoliken',
    name: 'Schreiphasen & Bauchweh bei Babys',
    aliases: ['Dreimonatskoliken', 'Koliken', 'Schreibaby', 'Blähungen'],
    emoji: '🍼',
    category: 'allgemein',
    ages: ['saeugling'],
    contagious: false,
    summary: 'Viele gesunde Babys schreien in den ersten Monaten viel – oft am Abend und scheinbar grundlos. Das ist sehr belastend, geht aber meist bis zum 4. Monat vorbei.',
    symptoms: ['unruhe', 'bauchschmerzen'],
    signs: ['Langes, schwer zu beruhigendes Schreien, oft am Spätnachmittag oder Abend', 'Anziehen der Beine, rotes Gesicht, geballte Fäuste', 'Ansonsten gesundes, gut gedeihendes Baby'],
    causes: 'Nicht genau geklärt. Reifung von Verdauung und Nervensystem und Schwierigkeiten bei der Selbstberuhigung spielen eine Rolle.',
    duration: 'Beginn meist in den ersten Wochen, Höhepunkt um die 6. Woche, Besserung bis zum 3.–4. Monat.',
    care: ['Feste Tagesabläufe, Reize reduzieren', 'Tragen, sanftes Schaukeln, weißes Rauschen', 'Fliegergriff, Bauchmassage im Uhrzeigersinn', 'Wenn du nicht mehr kannst: Baby sicher ins Bett legen und kurz den Raum verlassen. Niemals schütteln!'],
    treatment: 'Die Wirkung von Tropfen gegen Blähungen ist nicht sicher belegt. Viele Städte haben Schreiambulanzen und Elternberatungen.',
    doctor: ['Das Baby trinkt schlecht, nimmt nicht zu, erbricht häufig', 'Das Schreien klingt schrill oder anders als sonst', 'Du fühlst dich überfordert – Hilfe zu holen ist ein Zeichen von Stärke'],
    emergency: ['Fieber bei Babys unter 3 Monaten', 'Das Baby ist schlapp, hat Blut im Stuhl oder grünes Erbrechen', 'Das Baby wurde geschüttelt'],
    kita: '—',
    prevention: 'Nicht sicher vermeidbar. Unterstützung früh annehmen.',
    sources: [SRC.kgi, SRC.nhs('colic', 'Colic')]
  }
];

const EMERGENCY_NUMBERS = [
  { number: '112', label: 'Notruf (Rettungsdienst)', note: 'Lebensgefahr, Atemnot, Bewusstlosigkeit, Krampf > 5 Min.' },
  { number: '116 117', label: 'Ärztlicher Bereitschaftsdienst', note: 'Nachts, am Wochenende und an Feiertagen, wenn es nicht bis morgen warten kann' },
  { number: 'Giftnotruf', label: 'Giftinformationszentrum', note: 'Regional, z. B. Berlin/Brandenburg 030 19240' }
];

window.KKB_DATA = { SYMPTOMS, CATEGORIES, AGE_GROUPS, DISEASES, EMERGENCY_NUMBERS };
